[package]
name = "bevy_cells"
version = "0.1.0"
edition = "2021"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
aery = "0.4"
bevy = {version = "0.11.3", default-features = false}